//! Split-payment intent model for multi-leg streaming sats flows.
//!
//! A `SplitPaymentIntent` declares N legs from one source wallet.
//! The scheduler emits one intent per period tick; each leg is executed
//! idempotently by the wallet layer using `(intent_id, leg_index)` as the key.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// A single recipient leg within a split payment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SplitLeg {
    /// Index within the intent (0-based). Forms the idempotency key with `intent_id`.
    pub leg_index: u32,
    /// Recipient's Nostr public key (hex).
    pub recipient_npub_hex: String,
    /// Millisatoshis to send to this recipient.
    pub msats: u64,
    /// Maximum fee budget in msats for this leg.
    pub max_fee_msats: u64,
    /// Optional memo attached to the payment.
    pub memo: Option<String>,
    /// If `true`, credit via LSP Stable-Channel; if `false`, use NIP-57 zap fallback.
    pub prefer_stable_channel: bool,
}

/// A single period dispatch of a streaming sats flow.
///
/// Generated by `uplink-scheduler` on each tick and consumed by `uplink-wallet`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SplitPaymentIntent {
    /// UUID hex identifying this intent (persisted for idempotency).
    pub intent_id: String,
    /// The stream this intent belongs to (references a kind-30901 event).
    pub stream_id: String,
    /// Period index (monotonically increasing, starts at 0).
    pub period_index: u64,
    /// Source wallet ID.
    pub source_wallet_id: String,
    /// All legs to execute.
    pub legs: Vec<SplitLeg>,
    /// Unix timestamp when this intent was generated.
    pub created_at_unix: u64,
    /// Work session that authorized this interval, for in-office streaming.
    /// `None` for one-time and standard-recurring intents (ADR-U-008).
    #[serde(default)]
    pub session_id: Option<String>,
}

impl SplitPaymentIntent {
    /// Derive the idempotency key for a specific leg.
    /// Format: SHA-256 of `intent_id:leg_index` (hex).
    pub fn leg_idempotency_key(&self, leg_index: u32) -> String {
        let mut h = Sha256::new();
        h.update(self.intent_id.as_bytes());
        h.update(b":");
        h.update(leg_index.to_string().as_bytes());
        hex::encode(h.finalize())
    }

    /// Total msats committed across all legs (for budget-check purposes).
    pub fn total_msats(&self) -> u64 {
        self.legs.iter().map(|l| l.msats + l.max_fee_msats).sum()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn idempotency_key_is_deterministic() {
        let intent = SplitPaymentIntent {
            intent_id: "test-intent-001".into(),
            stream_id: "stream-001".into(),
            period_index: 3,
            source_wallet_id: "wallet-001".into(),
            legs: vec![],
            created_at_unix: 1_700_000_000,
            session_id: None,
        };
        let key_a = intent.leg_idempotency_key(0);
        let key_b = intent.leg_idempotency_key(0);
        assert_eq!(key_a, key_b);
        assert_ne!(key_a, intent.leg_idempotency_key(1));
    }
}
